spring.application.name=demo

# Azure Storage Table Configuration
azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
azure.storage.tables.cep-table=${AZURE_STORAGE_TABLES_CEP_TABLE}

# Server Configuration
server.port=8080
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true