spring.application.name=cep-api

azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
azure.storage.tables.cep-table=${AZURE_STORAGE_TABLES_CEP_TABLE:ceps}

spring.http.clients.connect-timeout=${HTTP_CLIENT_CONNECT_TIMEOUT:1s}
spring.http.clients.read-timeout=${HTTP_CLIENT_READ_TIMEOUT:2s}

server.port=8080
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
