spring.application.name=demo

# Azure Storage Table Configuration
azure.storage.tables.endpoint=${AZURE_STORAGE_TABLES_ENDPOINT}
azure.storage.tables.cep-table=${AZURE_STORAGE_TABLES_CEP_TABLE}

# Server Configuration
server.port=8080